use farmers_market

db.farmers_market.drop()

db.farmers_market.insert([
	{"market_name":"Bissel Gardens Farmers' Market","days":"Wednesday & Saturday ","hours":"9am-5pm","borough":"Bronx"},
	{"market_name":"Bronx Borough Hall Greenmarket","days":"Tuesday ","hours":"8am-4pm","borough":"Bronx"},
	{"market_name":"Crotona Park Greenmarket","days":"Saturday","hours":"8am-3pm","borough":"Bronx"},
	{"market_name":"Harvest Home Co-op City Farmers' Market","days":"Saturday","hours":"8am-4pm","borough":"Bronx"},
	{"market_name":"Harvest Home Echo Park Market","days":"Wednesday","hours":"8am-4pm","borough":"Bronx"},
	{"market_name":"Harvest Home Forest Avenue Farmers' Market","days":"Wednesday","hours":"8am-4pm","borough":"Bronx"},
	{"market_name":"Harvest Home Jacobi Hospital Farmers' Market","days":"Tuesday","hours":"8am-4pm","borough":"Bronx"},
	{"market_name":"Harvest Home Jerome Avenue Market","days":"Friday","hours":"8am-4pm","borough":"Bronx"},
	{"market_name":"Harvest Home Mt. Eden Farmers' Market","days":"Thursday","hours":"8am-4pm","borough":"Bronx"},
	{"market_name":"Harvest Home North Central Bronx Farmers' Market","days":"Wednesday","hours":"8am-4pm","borough":"Bronx"},
	{"market_name":"Harvest Home Sunday Farmers' Market","days":"Sunday","hours":"8am-4pm","borough":"Bronx"},
	{"market_name":"Harvest Home Throgs Neck Market","days":"Saturday","hours":"10am-5pm","borough":"Bronx"},
	{"market_name":"Hunts Point Farmers' Market","days":"Wednesday & Saturday ","hours":"8am-5pm","borough":"Bronx"},
	{"market_name":"Inwood Go Green Farmers' Market","days":"Tuesday","hours":"3pm-7pm","borough":"Bronx"},
	{"market_name":"Kingsbridge Heights Youthmarket","days":"Friday","hours":"12pm-6pm","borough":"Bronx"},
	{"market_name":"La Familia Verde Farmers' Market","days":"Tuesday","hours":"8am-2pm","borough":"Bronx"},
	{"market_name":"La Finca del Sur/South Bronx Farmers' Market","days":"Saturday","hours":"9am-2pm","borough":"Bronx"},
	{"market_name":"Learn It, Grow It, Eat It Youthmarket","days":"Wednesday","hours":"10am-3pm","borough":"Bronx"},
	{"market_name":"Lincoln Hospital Greenmarket","days":"Tuesday & Friday ","hours":"8am-3pm","borough":"Bronx"},
	{"market_name":"Little Green Market ","days":"Wednesday","hours":"10am-6pm","borough":"Bronx"},
	{"market_name":"Marble Hill Youthmarket","days":"Thursday","hours":"2pm-6pm","borough":"Bronx"},
	{"market_name":"Mott Haven Farmers' Market ","days":"Wednesday ","hours":"9am- 5pm","borough":"Bronx"},
	{"market_name":"New York Botanical Gardens Greenmarket","days":"Wednesday ","hours":"9am-3pm","borough":"Bronx"},
	{"market_name":"Northeast Bronx Farmers' Market","days":"Saturday","hours":"8am-5:30pm","borough":"Bronx"},
	{"market_name":"Parkchester Greenmarket","days":"Friday","hours":"8am-3pm","borough":"Bronx"},
	{"market_name":"Poe Park Greenmarket","days":"Tuesday ","hours":"8am-3pm","borough":"Bronx"},
	{"market_name":"Riverdale Youthmarket","days":"Thursday","hours":"3pm-7pm","borough":"Bronx"},
	{"market_name":"Taqwa Community Farmers' Market","days":"Saturday ","hours":"8am-4pm","borough":"Bronx"},
	{"market_name":"The Heights Community Farmers' Market","days":"Thursday","hours":"10am-3pm","borough":"Bronx"},
	{"market_name":"Riverdale Y Sunday Farmers' Market","days":"Sunday","hours":"9am-1pm","borough":"Bronx"},
	{"market_name":"Wholesale Greenmarket","days":"Tuesday-Saturday","hours":"2am-8am","borough":"Bronx"},
	{"market_name":"Roberto Clemente Plaza Youthmarket","days":"Wednesday","hours":"9am-3pm","borough":"Bronx"},
	{"market_name":"Bartel-Pritchard Square Greenmarket","days":"Wednesday","hours":"8am-3pm","borough":"Brooklyn"},
	{"market_name":"Bay Ridge Greenmarket","days":"Saturday ","hours":"8am-3pm","borough":"Brooklyn"},
	{"market_name":"BFM I Satellite at Wyckoff Heights Medical Center","days":"Wednesday","hours":"12pm-5pm","borough":"Brooklyn"},
	{"market_name":"BFM II Satellite at Irving Square Park","days":"Saturday","hours":"11am-4pm","borough":"Brooklyn"},
	{"market_name":"BFM III Satellite at Bushwick Campus","days":"Thursday","hours":"12pm-5pm","borough":"Brooklyn"},
	{"market_name":"Boro Park Greenmarket","days":"Thursday","hours":"8am-2pm","borough":"Brooklyn"},
	{"market_name":"Brooklyn Borough Hall Greenmarket","days":"Tuesday, Thursday & Saturday","hours":"8am-3pm","borough":"Brooklyn"},
	{"market_name":"Brownsville Community Farmers' Market","days":"Saturday ","hours":" 8:30am-3pm","borough":"Brooklyn"},
	{"market_name":"Brownsville Pitkin Avenue Youthmarket","days":"Saturday ","hours":"9:30am-3:30pm","borough":"Brooklyn"},
	{"market_name":"Brownsville Recreational Center Youthmarket","days":"Saturday","hours":"10:30am-2:30pm","borough":"Brooklyn"},
	{"market_name":"Brownsville Youthmarket","days":"Friday","hours":"1pm-6pm","borough":"Brooklyn"},
	{"market_name":"Bushwick Farmers' Market I","days":"Wednesday ","hours":"10am-6pm","borough":"Brooklyn"},
	{"market_name":"Bushwick Farmers' Market II at Maria Hernandez Park ","days":"Saturday ","hours":"9am-5pm ","borough":"Brooklyn"},
	{"market_name":"Bushwick Farmers' Market III ","days":"Thursday","hours":"10am-6pm","borough":"Brooklyn"},
	{"market_name":"Carroll Gardens Greenmarket","days":"Sunday","hours":"8am-3pm","borough":"Brooklyn"},
	{"market_name":"Cooper Park Farmers' Market","days":"Sunday","hours":"11am-4pm","borough":"Brooklyn"},
	{"market_name":"Cortelyou Greenmarket","days":"Sunday","hours":"8am-2pm","borough":"Brooklyn"},
	{"market_name":"Cypress Hills Youthmarket","days":"Friday","hours":"1pm-7pm","borough":"Brooklyn"},
	{"market_name":"East New York Farm Stand","days":"Wednesday","hours":"3:30pm-6:30pm","borough":"Brooklyn"},
	{"market_name":"East New York Farmers' Market ","days":"Saturday ","hours":"9am-3pm","borough":"Brooklyn"},
	{"market_name":"Fort Greene Park Greenmarket","days":"Saturday ","hours":"8am-3pm","borough":"Brooklyn"},
	{"market_name":"Graham Avenue Farmers' Market","days":"Saturday & Sunday ","hours":"8am-5pm","borough":"Brooklyn"},
	{"market_name":"Grand Army Plaza Greenmarket","days":"Saturday","hours":"8am-4pm","borough":"Brooklyn"},
	{"market_name":"Greenpoint/ McCarren Park Greenmarket","days":"Saturday","hours":"8am-3pm","borough":"Brooklyn"},
	{"market_name":"Harvest Home Coney Island Hospital Farmers Market","days":"Friday","hours":"8am-4pm","borough":"Brooklyn"},
	{"market_name":"Harvest Home Lutheran Hospital Farmers Market","days":"Thursday","hours":"8am-4pm","borough":"Brooklyn"},
	{"market_name":"Hattie Carthan After Church Farmers' Market","days":"Sunday","hours":"1pm-6pm","borough":"Brooklyn"},
	{"market_name":"Hattie Carthan Community Farmers' Market ","days":"Saturday ","hours":"9am-3pm","borough":"Brooklyn"},
	{"market_name":"High School for Public Service Youth Farmers' Market","days":"Wednesday","hours":"2:30pm-6:30pm","borough":"Brooklyn"},
	{"market_name":"Isabahlia Farmers' Market","days":"Saturday","hours":"8am-4pm","borough":"Brooklyn"},
	{"market_name":"Kensington Youthmarket","days":"Saturday","hours":"9am-3pm","borough":"Brooklyn"},
	{"market_name":"Malcolm X Blvd Farmers' Market","days":"Saturday ","hours":"8am-3pm","borough":"Brooklyn"},
	{"market_name":"Medgar Evers College Farmers' Market","days":"Wednesday","hours":"11am-6pm","borough":"Brooklyn"},
	{"market_name":"Myrtle Avenue Community-Run Farm Stand","days":"Wednesday","hours":"4pm-7pm","borough":"Brooklyn"},
	{"market_name":"Red Hook Farmers' Market","days":"Saturday ","hours":"10am-3pm","borough":"Brooklyn"},
	{"market_name":"Seeds in the Middle Farmers' Market","days":"Thursday","hours":"12pm-7pm","borough":"Brooklyn"},
	{"market_name":"Sunset Park Greenmarket","days":"Saturday","hours":"8am-2pm","borough":"Brooklyn"},
	{"market_name":"The Foodshed Farmers' Market","days":"Sunday","hours":"11am-5pm","borough":"Brooklyn"},
	{"market_name":"Urban Oasis Farmers' Market","days":"Wednesday","hours":"2pm-5:30pm","borough":"Brooklyn"},
	{"market_name":"Walt L Shamel Farmers' Market","days":"Saturday","hours":"8am-2pm","borough":"Brooklyn"},
	{"market_name":"Weeksville Farmers' Market ","days":"Saturday","hours":"9am-4pm","borough":"Brooklyn"},
	{"market_name":"Williamsburg Greenmarket","days":"Thursday ","hours":"8am-2pm","borough":"Brooklyn"},
	{"market_name":"Windsor Terrace - PS 154 Greenmarket","days":"Sunday","hours":"9am-4pm","borough":"Brooklyn"},
	{"market_name":"Coney Island Farmers' Market","days":"Sunday","hours":"7am-3pm","borough":"Brooklyn"},
	{"market_name":"Flatbush Caton Merchants Mart Farmers' Market","days":"Monday-Saturday & Sunday","hours":"10am-8pm & 10am-6pm","borough":"Brooklyn"},
	{"market_name":"McGolrick Park Farmers' Market","days":"Sunday","hours":"11am-4pm","borough":"Brooklyn"},
	{"market_name":"Park Slope Farmers' Market","days":"Sunday","hours":"11am-5pm","borough":"Brooklyn"},
	{"market_name":"Project Eats Community Market","days":"Friday","hours":"1pm-7pm","borough":"Brooklyn"},
	{"market_name":"La Marqueta Farmers' Market","days":"Monday-Wednesday & Thursday-Saturday ","hours":"8am-5pm & 8am-6 pm","borough":"Manhattan"},
	{"market_name":"125th Street Fresh Connect Farmers' Market","days":"Tuesday ","hours":"10am-7pm","borough":"Manhattan"},
	{"market_name":"57th Street Greenmarket","days":"Wednesday","hours":"8am-6pm","borough":"Manhattan"},
	{"market_name":"79th Street Greenmarket","days":"Sunday","hours":"8am-5pm","borough":"Manhattan"},
	{"market_name":"82nd Street Greenmarket","days":"Saturday","hours":"9am-3pm","borough":"Manhattan"},
	{"market_name":"92nd Street Greenmarket","days":"Sunday ","hours":"9am-4pm","borough":"Manhattan"},
	{"market_name":"97th Street Greenmarket","days":"Friday ","hours":"8am-2pm","borough":"Manhattan"},
	{"market_name":"Abingdon Square Greenmarket","days":"Saturday ","hours":"8am-2pm","borough":"Manhattan"},
	{"market_name":"Bowling Green Greenmarket","days":"Tuesday & Thursday","hours":"8am-5pm","borough":"Manhattan"},
	{"market_name":"City Hall Greenmarket","days":"Tuesday & Friday ","hours":"8am-4pm","borough":"Manhattan"},
	{"market_name":"Columbia University Greenmarket","days":"Thursday & Sunday ","hours":"8am-3pm","borough":"Manhattan"},
	{"market_name":"Dag Hammarskjold Plaza Greenmarket","days":"Wednesday","hours":"8am-4pm","borough":"Manhattan"},
	{"market_name":"Fort Washington Greenmarket","days":"Tuesday","hours":"8am-4pm","borough":"Manhattan"},
	{"market_name":"Grass Roots Farmers' Market","days":"Tuesday & Saturday","hours":"9am-4pm","borough":"Manhattan"},
	{"market_name":"Harlem Harvest Farmers' Market","days":"Tuesday & Saturday ","hours":"8am-5pm","borough":"Manhattan"},
	{"market_name":"Harvest Home East Harlem Farmers' Market","days":"Thursday","hours":"8am-4pm","borough":"Manhattan"},
	{"market_name":"Harvest Home Metropolitan Market","days":"Friday ","hours":"8am-4pm","borough":"Manhattan"},
	{"market_name":"Harvest Home Mt. Morris Park Market","days":"Saturday","hours":"8am-4pm","borough":"Manhattan"},
	{"market_name":"Harvest Home Murray Hill Farmers' Market","days":"Friday","hours":"8am-4pm","borough":"Manhattan"},
	{"market_name":"Harvest Home West Harlem Farmers' Market","days":"Tuesday","hours":"8am-4pm","borough":"Manhattan"},
	{"market_name":"Inwood Church Farmers' Market","days":"Wednesday","hours":"2pm-6pm","borough":"Manhattan"},
	{"market_name":"Inwood Park Greenmarket","days":"Saturday ","hours":"8am-3pm","borough":"Manhattan"},
	{"market_name":"Lower East Side Youthmarket","days":"Thursday","hours":"3pm-7pm","borough":"Manhattan"},
	{"market_name":"Morningside Park Farmers' Market","days":"Saturday ","hours":"9am-5pm","borough":"Manhattan"},
	{"market_name":"Mt. Sinai Hospital Greenmarket","days":"Wednesday","hours":"8am-4pm","borough":"Manhattan"},
	{"market_name":"New Amsterdam Farmers' Market","days":"Sunday","hours":"11am-4pm","borough":"Manhattan"},
	{"market_name":"PS 11 Farm Market","days":"Wednesday","hours":"8am-10am","borough":"Manhattan"},
	{"market_name":"St. Mark's Church Greenmarket","days":"Tuesday","hours":"8am-7pm","borough":"Manhattan"},
	{"market_name":"Staten Island Ferry/Whitehall Greenmarket","days":"Tuesday & Friday ","hours":"8am-7pm","borough":"Manhattan"},
	{"market_name":"Stuyvesant Town Greenmarket","days":"Sunday","hours":"9:30am-4pm","borough":"Manhattan"},
	{"market_name":"Tompkins Square Greenmarket","days":"Sunday","hours":"8am-6pm","borough":"Manhattan"},
	{"market_name":"Tribeca Greenmarket","days":"Wednesday & Saturday ","hours":"8am-3pm","borough":"Manhattan"},
	{"market_name":"Tucker Square Greenmarket","days":"Thursday & Saturday","hours":"8am-5pm","borough":"Manhattan"},
	{"market_name":"Union Square Greenmarket","days":"Monday, Wednesday, Friday & Saturday","hours":"8am-6pm","borough":"Manhattan"},
	{"market_name":"Washington Heights 175th Street Greenmarket","days":"Thursday ","hours":"8am-4pm","borough":"Manhattan"},
	{"market_name":"Downton PATH Greenmarket","days":"Thursday","hours":"8am-6pm","borough":"Manhattan"},
	{"market_name":"NY/NJ Port Authority Greenmarket","days":"Thursday","hours":"8am-6pm","borough":"Manhattan"},
	{"market_name":"Rockefeller Center Greenmarket","days":"Wednesday, Thursday & Friday","hours":"8am-6pm","borough":"Manhattan"},
	{"market_name":"South Village Farmers' Market","days":"Monday, Wednesday & Friday","hours":"10am-7pm","borough":"Manhattan"},
	{"market_name":"Astoria Greenmarket","days":"Wednesday","hours":"8am-3pm","borough":"Queens"},
	{"market_name":"Atlas Park Greenmarket","days":"Saturday","hours":"8am-3pm","borough":"Queens"},
	{"market_name":"Corona Greenmarket","days":"Friday","hours":"8am-3pm","borough":"Queens"},
	{"market_name":"Culinary Kids Garden Farmers' Market I","days":"Saturday","hours":"10am-3pm","borough":"Queens"},
	{"market_name":"Culinary Kids Garden Farmers' Market II","days":"Saturday","hours":"10am-5pm","borough":"Queens"},
	{"market_name":"Douglaston Greenmarket","days":"Sunday","hours":"8am-3pm","borough":"Queens"},
	{"market_name":"Elmhurst Hospital Greenmarket","days":"Tuesday","hours":"8am-5pm","borough":"Queens"},
	{"market_name":"Harvest Home Roy Wilkins Park Farmers Market","days":"Saturday","hours":"8am-4pm","borough":"Queens"},
	{"market_name":"Jackson Heights Greenmarket","days":"Sunday","hours":"8am-3pm","borough":"Queens"},
	{"market_name":"Jamaica Farmers Market","days":"Friday & Saturday ","hours":"8:30am-4pm","borough":"Queens"},
	{"market_name":"Pomonok Farmers' Market","days":"Thursday","hours":"10am-5:30pm","borough":"Queens"},
	{"market_name":"Queens Botanical Garden Farmers' Market","days":"Friday","hours":"8:30am-4pm","borough":"Queens"},
	{"market_name":"Ridgewood Youthmarket","days":"Saturday","hours":"10am-3pm","borough":"Queens"},
	{"market_name":"Socrates Sculpture Park Greenmarket","days":"Saturday","hours":"8am-4pm","borough":"Queens"},
	{"market_name":"Sunnyside Gardens Greenmarket","days":"Saturday","hours":"8am-4pm","borough":"Queens"},
	{"market_name":"Joseph Addabbo Family Health Center's Farmers' Market","days":"Saturday","hours":"8:30am-2pm","borough":"Queens"},
	{"market_name":"St. George Greenmarket","days":"Saturday","hours":"8am-2pm","borough":"Staten Island"},
	{"market_name":"Staten Island Mall Greenmarket","days":"Saturday","hours":"9am-4pm","borough":"Staten Island"}
])
